"""Command-line entrypoint matching the Analysis Core process contract."""

import argparse
import hashlib
import json
import os
import sys
import tempfile
import time
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from docreview_mock import __version__
from docreview_mock.scenario import (
    ScenarioConfigurationError,
    load_scenario_configuration,
    resolve_scenario,
)

SCHEMA_VERSION = "1.0"


def _configure_utf8_streams() -> None:
    """Use stable UTF-8 output even when stdout/stderr are redirected on Windows."""

    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is not None:
            reconfigure(encoding="utf-8")


def _non_empty_run_id(value: str) -> str:
    if not value or len(value) > 128:
        raise argparse.ArgumentTypeError("run id must contain 1 to 128 characters")
    return value


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="docreview")
    commands = parser.add_subparsers(dest="command", required=True)

    analyze = commands.add_parser("analyze", help="analyze one document")
    analyze.add_argument("--file", required=True, type=Path)
    analyze.add_argument("--pack", required=True, type=Path)
    analyze.add_argument("--model-config", type=Path)
    analyze.add_argument("--run-id", required=True, type=_non_empty_run_id)
    analyze.add_argument("--output", type=Path)
    analyze.add_argument("--artifacts-dir", type=Path)
    analyze.add_argument("--include-rejected", action="store_true")

    commands.add_parser("version", help="print mock and contract versions")
    return parser


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _completed_result(args: argparse.Namespace, elapsed_ms: int) -> dict[str, Any]:
    document_path: Path = args.file
    pack_path: Path = args.pack
    return {
        "schema_version": SCHEMA_VERSION,
        "run_id": args.run_id,
        "status": "completed",
        "document": {
            "filename": document_path.name,
            "document_type": document_path.suffix.lstrip(".").lower() or "unknown",
            "sha256": _sha256(document_path),
        },
        "engine": {"version": __version__},
        "review_pack": {"id": pack_path.stem or pack_path.name, "version": "mock-1.0"},
        "model": {"name": "mock", "prompt_versions": {}},
        "findings": [],
        "summary": {
            "total_candidates": 0,
            "verified_candidates": 0,
            "returned_findings": 0,
            "critical": 0,
            "high": 0,
            "medium": 0,
            "low": 0,
        },
        "warnings": [
            {
                "code": "MOCK_RESULT",
                "message": "Result generated by Mock Analysis Core.",
            }
        ],
        "timings": {"total_ms": elapsed_ms},
    }


def _serialize_json(payload: dict[str, Any]) -> str:
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + "\n"


def _prepare_scenario_content(content: str, args: argparse.Namespace, elapsed_ms: int) -> str:
    """Bind reusable JSON fixtures to the current invocation."""

    try:
        payload = json.loads(content)
    except json.JSONDecodeError:
        return content
    if not isinstance(payload, dict):  # pragma: no cover - fixture generator invariant
        return content

    payload["run_id"] = args.run_id
    if payload.get("status") == "completed":
        document_path: Path = args.file
        pack_path: Path = args.pack
        payload["document"] = {
            "filename": document_path.name,
            "document_type": document_path.suffix.lstrip(".").lower() or "unknown",
            "sha256": _sha256(document_path),
        }
        payload["review_pack"]["id"] = pack_path.stem or pack_path.name
        payload["timings"]["total_ms"] = elapsed_ms
    return _serialize_json(payload)


def _write_atomically(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            prefix=f".{path.name}.",
            suffix=".tmp",
            dir=path.parent,
            delete=False,
        ) as temporary:
            temporary.write(content)
            temporary.flush()
            os.fsync(temporary.fileno())
            temporary_path = Path(temporary.name)
        os.replace(temporary_path, path)
    except BaseException:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)
        raise


def _run_analyze(args: argparse.Namespace) -> int:
    started_at = time.monotonic()
    document_path: Path = args.file
    pack_path: Path = args.pack
    if not document_path.is_file():
        print("document is unavailable", file=sys.stderr)
        return 3
    if not pack_path.exists():
        print("review pack is unavailable", file=sys.stderr)
        return 4

    try:
        scenario_configuration = load_scenario_configuration()
    except ScenarioConfigurationError as error:
        print(f"mock configuration error: {error}", file=sys.stderr)
        return 2

    if scenario_configuration is not None:
        time.sleep(scenario_configuration.delay_ms / 1000)
        scenario = resolve_scenario(scenario_configuration.name)
        elapsed_ms = max(0, round((time.monotonic() - started_at) * 1000))
        if scenario.stdout is not None:
            content = _prepare_scenario_content(scenario.stdout, args, elapsed_ms)
            if args.output is not None:
                _write_atomically(args.output, content)
            sys.stdout.write(content)
            sys.stdout.flush()
        print(scenario.stderr, file=sys.stderr)
        return scenario.exit_code

    elapsed_ms = max(0, round((time.monotonic() - started_at) * 1000))
    content = _serialize_json(_completed_result(args, elapsed_ms))
    if args.output is not None:
        _write_atomically(args.output, content)
    sys.stdout.write(content)
    sys.stdout.flush()
    print(f"mock analysis completed for run {args.run_id}", file=sys.stderr)
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    """Run the CLI and return its process exit code."""

    _configure_utf8_streams()
    args = _build_parser().parse_args(argv)
    if args.command == "version":
        sys.stdout.write(
            _serialize_json(
                {
                    "name": "docreview-mock-analysis-core",
                    "version": __version__,
                    "schema_version": SCHEMA_VERSION,
                }
            )
        )
        return 0
    if args.command == "analyze":
        return _run_analyze(args)
    raise AssertionError(f"Unsupported command: {args.command}")  # pragma: no cover


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
